name: tests
on:
  push:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '>=1.20.0'
      - uses: actions/checkout@v2
      - name: run tests with coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...